;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;  The ink flow down into a dark puddle. Just move your hand
;  write a way into his heart
;
;==========================================================

; @! General config ---------------------------------------

[colors]
background = #29628f
foreground = #e6e6e6
flower-active = #ffffff
flower-occupied = #b3b3b3
flower-empty = #666666

[settings]
screenchange-reload = true
pseudo-transparency = true

[bar/bar1]
monitor = ${env:MONITOR:}

width = 100%
height = 24pt
radius = 10

background = ${colors.background}
foreground = ${colors.foreground}
line-size = 3pt
font-0 = JetBrainsMono Nerd Font:weight=bold:size=11;2

cursor-click = pointer
cursor-scroll = ns-resize

border-size = 8pt
border-color = #00000000
padding-left = 4
padding-right = 4

enable-ipc = true

modules-left = clock space date space separator space xwindow
modules-center = xworkspaces
modules-right = systray space separator space wlan space separator space pulseaudio space separator space battery

; @! Utils --------------------------------------------------

[module/space]
type = custom/text
format = "  "

[module/separator]
type = custom/text
format = "|"
content-foreground = ${colors.disabled}

; @! Left modules -------------------------------------------

[module/clock]
type = internal/date
interval = 1
time =  %H:%M:%S
label = %time%

[module/date]
type = internal/date
date =  %d-%m-%Y
label = %date%

[module/xwindow]
type = internal/xwindow
label = %title:0:30:...%

; @! Center modules -----------------------------------------

[module/xworkspaces]
type = internal/xworkspaces

label-active = 󰴈
label-active-foreground = ${colors.flower-active}
label-active-padding = 1
label-active-font = 1

label-occupied = 󰴈
label-occupied-foreground = ${colors.flower-occupied}
label-occupied-padding = 1
label-occupied-font = 1

label-empty = 󰴈
label-empty-foreground = ${colors.flower-empty}
label-empty-padding = 1
label-empty-font = 1

; @! Right modules ------------------------------------------

[module/systray]
type = internal/tray

format-margin = 8pt
tray-spacing = 16pt

[network-base]
type = internal/network
interval = 5
format-disconnected = <label-disconnected>
label-disconnected = %ifname% disconnected

[module/wlan]
inherit = network-base
interface-type = wireless

format-connected = <ramp-signal> <label-connected>
label-connected = %{A1:$HOME/.config/scripts/net_menu.sh:}%essid%%{A}

ramp-signal-0 = 󰤯
ramp-signal-1 = 󰤟
ramp-signal-2 = 󰤢
ramp-signal-3 = 󰤥
ramp-signal-4 = 󰤨

format-disconnected = <label-disconnected>
label-disconnected = 󰖪 No internet

[module/eth]
inherit = network-base
interface-type = wired

format-connected = 󰈀 <label-connected>
label-connected = %ifname% %local_ip%

format-disconnected = <label-disconnected>
label-disconnected = %ifname% disconnected

[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix-foreground = ${colors.primary}
format-volume = <ramp-volume> <label-volume>
label-volume = %percentage%%

ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰕾

label-muted = 󰝟 muted
label-muted-foreground = ${colors.foreground}

click-right = pavucontrol

[module/battery]
type = internal/battery
full-at = 99
low-at = 10

battery = BAT0
adapter = ADP0

poll-interval = 5

format-discharging = <ramp-capacity> <label-discharging>
label-discharging = %percentage%%

format-charging = <ramp-capacity> 󱐋 <label-charging>
label-charging = %percentage%%

label-full = 󱈑 %percentage%%

ramp-capacity-0 = 
ramp-capacity-1 = 
ramp-capacity-2 = 
ramp-capacity-3 = 
ramp-capacity-4 = 

